### ISSUE TITLE
Manual password input doesn't work

### ISSUE THREAD

**Issue by rifle2000** [gastamper/dracut-tpm#4]
On Centos 7 manual password input after tpm_nvread error doesn't work. Nv hook tries to input password 3 times when PCR doesn't match and even if I implement exit from script on tpm read error and input password from keyboard something doesn't work and boot stucks on mounting fs.

**Comment by rifle2000** [comment]
I solved it by checking that nvread was successfull and if not break loop. Exit is messing things out. It is not perfect because script is constantly looping in background but it works. You can enter manually password and boot continues.

**Comment by gastamper** [comment]
@rifle2000 
Minor FYI but now that clevis supports TPM 2.0 (and I have no 1.2 machines to work with), this repository is effectively un-maintained.  I'd suggest migrating to clevis' TPM 2.0 support if possible.

That said, this is actually a bug inherited from clevis' dracut hooks; good that you found a way to fix it.  I don't intend to resolve (unless you'd like to submit a pull request) since you can just reboot and enter the password manually early enough.  In my experience manual password entry only fails if it loops for some noticeable period of time.
